[project]
name = "lumos"
version = "0.7.2"

[tool.poetry]
authors = ["lumos-dev"]
description = "Lumos command line interface."
name = "lumos"
version = "0.7.2"

[tool.poetry.dependencies]
python = "3.10.6"
annotated-types = "0.6.0"
certifi = "2024.2.2"
charset-normalizer = "3.3.2"
click = "8.1.7"
colorama = "0.4.6"
idna = "3.6"
pick = "2.2.0"
pydantic = "2.6.1"
pydantic_core = "2.16.2"
pytz = "2024.1"
requests = "2.31.0"
shellingham = "1.5.4"
tabulate = "0.9.0"
typer = "0.9.0"
types-pytz = "2024.1.0.20240203"
types-tabulate = "0.9.0.20240106"
typing-extensions = ">=3.7.4.3"
typing_extensions = "4.9.0"
urllib3 = "2.2.0"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.0"
