name: Build Binaries

on:
  push:
    branches:
      - main
    tags:
      - v*    
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu24-4cpu-amd64
            platform: linux-amd64
            arch: x64
          - runner: ubuntu24-4cpu-arm64
            platform: linux-arm64
            arch: aarch64
          - runner: macos-latest
            platform: macos-arm64
            arch: arm64
          - runner: windows-latest
            platform: windows
            arch: x64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: latest
          enable-cache: true

      - name: Install dependencies
        shell: bash
        run: uv sync

      - name: Build binary
        shell: bash
        run: |
          uv run pyinstaller lumos/__main__.py
          if [[ "${{ matrix.platform }}" == "windows" ]]; then
            mv ./dist/__main__/__main__.exe ./dist/__main__/lumos.exe
          else
            mv ./dist/__main__/__main__ ./dist/__main__/lumos
          fi
          tar -czf lumos-${{ matrix.platform }}.tar.gz -C ./dist/__main__ .
          mv lumos-${{ matrix.platform }}.tar.gz ./dist/__main__/
          sha256sum ./dist/__main__/lumos-${{ matrix.platform }}.tar.gz | cut -d ' ' -f1 > ./dist/__main__/lumos-${{ matrix.platform }}.tar.gz.sha256


      - name: Display SHA256
        shell: bash
        run: |
          SHA=$(cat ./dist/__main__/lumos-${{ matrix.platform }}.tar.gz.sha256)
          echo "*******************"
          echo "File SHA: $SHA"
          echo "*******************"

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v4
        with:
          name: lumos-${{ matrix.platform }}
          path: |
            dist/__main__/lumos-*.tar.gz
            dist/__main__/lumos-*.tar.gz.sha256
          retention-days: 90

      - name: Upload artifacts to release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh release upload ${{ github.ref_name }} \
            dist/__main__/lumos-*.tar.gz \
            dist/__main__/lumos-*.tar.gz.sha256
